ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/psf/black
    rev: 22.12.0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3  # Should be a command that runs python3.6+

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort
      files: \.py$
      args: [--profile=black]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: requirements-txt-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: forbid-new-submodules
      - id: check-builtin-literals
      - id: trailing-whitespace

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.19.2
    hooks:
      - id: check-jsonschema
        name: "Check GitHub Workflows"
        files: ^\.github/workflows/
        types: [yaml]
        args: ["--schemafile", "https://json.schemastore.org/github-workflow"]
        stages: [manual]
